<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>piedteam_hocmienphi.service</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\piedteam-hocmienphi.repository\piedteam-hocmienphi.repository.csproj" />
    </ItemGroup>

</Project>
